on:
  push:

jobs:
  my_action:
    name: my actions
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
